# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02e00a1ca45728d72e0fe4edbec5e2ac88e056e9058f86f5ab6dbd8d156e0ea9236ca891cbc9ed646a11d3892f445c0ad66ac1486c67fff12457a73ecae9ba9a

test:
  secret_key_base: 09a1a28c5a3faf12e02468983051b3109dae23ebd6d828cc374c80848a17b9c7b8dcd19713a6338577377db48c1fe57fad3ed2e2e1d817a5c943e65fb1209485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
